name: Deploy Vite site to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VITE_BASE: "/"  # root since you’re using a custom apex domain
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      # SPA routing fallback (copy created by your postbuild; keep as belt-and-suspenders)
      - name: Ensure 404.html exists
        run: |
          if [ ! -f dist/404.html ]; then cp dist/index.html dist/404.html; fi
      # Custom domain
      - name: Add CNAME
        run: echo thevalorvenue.com > dist/CNAME
      # Cache-bust HTML so CDN picks new bundle filename
      - name: Bust CDN by appending timestamp comment
        run: echo "<!-- build $(date -u +%Y-%m-%dT%H:%M:%SZ) -->" >> dist/index.html
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
